### ISSUE TITLE
Update action not running due to inactivity

### ISSUE THREAD

**Issue by pboehnke-relativity** [cloudnative-pg/pgbouncer-containers#52]
We've run into a bug that was fixed in 1.23.1 (and introduced in 1.23.0 - https://www.pgbouncer.org/changelog.html#pgbouncer-123x)  and in looking through the github actions saw that the update one is disabled causing the image to be out of date. Can you please re-enable the update action so it produces a build with 1.23.1?

See status here: https://github.com/cloudnative-pg/pgbouncer-containers/actions/workflows/update.yml

![Image](https://github.com/user-attachments/assets/84245d1b-9be2-4d87-a0d8-f44143fff917)

**Comment by pboehnke-relativity** [comment]
Thank you for the quick response. That is too bad! Is another option to consider '-fixed' in the release name as valid for the action? Happy to put up a PR if it is

**Comment by pboehnke-relativity** [comment]
Nevermind my previous comment it looks like there is a release without the -fixed in the tag: https://github.com/pgbouncer/pgbouncer/releases/tag/pgbouncer_1_23_1

The two appear identical: ![Image](https://github.com/user-attachments/assets/dd9b9a54-6a9f-48b7-8f28-54c0fcf34fe9)

**Comment by sxd** [comment]
@pboehnke-relativity we will take a look into this and will let you know :D

**Comment by sxd** [comment]
Hey @NiccoloFei :D

**Comment by pboehnke-relativity** [comment]
Thank you so much!

**Comment by sxd** [comment]
hello @pboehnke-relativity 

We talked with @NiccoloFei and even if there's a tag with t no difference the one with the "-fixed" suffix is marked as the latest and in our automated process we look for the latest one, since they have been changing this for a couple of time already, we opened an issue here https://github.com/pgbouncer/pgbouncer/issues/1194 for them to clarify the idea behind having those weird tags for the release, also, we talked with @NiccoloFei and creating a fix for supporting something that it's not right will more than fix our issues but support the idea of doing stuff wrong, so we will not support it and this needs to be fixed on the pgbouncer side by them releasing the a proper semantic version for the tags and not making these tags that don't help at all

Regards!

**Comment by sxd** [comment]
Closing this with won't fix
